# Generated by Django 5.0.4 on 2026-04-06 12:00
from django.db import migrations, models
import django.db.models.deletion
import shared.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('behavior_type', models.CharField(choices=[('view', 'View'), ('cart', 'Add to Cart'), ('purchase', 'Purchase'), ('review', 'Review')], db_index=True, max_length=20)),
                ('product_id', models.UUIDField(db_index=True)),
                ('rating', models.FloatField(null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'user_behaviors',
                'indexes': [],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('ncf', 'Neural Collaborative Filtering'), ('content', 'Content-Based'), ('hybrid', 'Hybrid'), ('llm', 'LLM-Based')], max_length=20)),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(null=True)),
                ('precision', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('model_path', models.CharField(max_length=500)),
                ('config', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'recommendation_models',
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('embedding', models.JSONField()),
                ('feature_names', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_embeddings',
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('cache_key', models.CharField(max_length=200)),
                ('recommendations', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'recommendation_cache',
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
    ]
