# Generated by Django 5.0.4 on 2026-04-06 12:00
from django.db import migrations, models
import django.db.models.deletion
import shared.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.UUIDField(db_index=True, unique=True)),
                ('user_id', models.UUIDField(db_index=True, null=True, blank=True)),
                ('session_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversations',
                'indexes': [],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prompt_template', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'system_prompts',
                'ordering': ['-version'],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.UUIDField(db_index=True, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('retrieved_docs', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('used_rag', models.BooleanField(default=False)),
                ('feedback', models.IntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
                'indexes': [],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_type', models.CharField(max_length=100)),
                ('context_data', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='chatbot.conversation')),
            ],
            options={
                'db_table': 'conversation_contexts',
                'indexes': [],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('avg_conversation_length', models.FloatField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('satisfaction_score', models.FloatField(blank=True, null=True)),
                ('resolution_rate', models.FloatField(default=0)),
                ('rag_usage_count', models.IntegerField(default=0)),
                ('top_intents', models.JSONField(default=list)),
                ('language_distribution', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'chatbot_analytics',
                'ordering': ['-date'],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='IntentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('entities', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='chatbot.message')),
            ],
            options={
                'db_table': 'intent_predictions',
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
    ]
