# Generated by Django 5.0.4 on 2026-04-06 12:00
from django.db import migrations, models
import django.db.models.deletion
import shared.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faq_categories',
                'ordering': ['sort_order', 'name'],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('keywords', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='knowledge_base.faqcategory')),
            ],
            options={
                'db_table': 'faqs',
                'ordering': ['priority', '-created_at'],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('document_type', models.CharField(choices=[('policy', 'Policy'), ('guide', 'Guide'), ('manual', 'Manual'), ('faq', 'FAQ Document')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['category', 'title'],
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.UUIDField()),
                ('specifications', models.JSONField(default=dict)),
                ('manuals', models.JSONField(default=list)),
                ('troubleshooting', models.JSONField(default=list)),
                ('compatibility', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'product_knowledge',
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='VectorIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.BigIntegerField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('embedding', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'vector_index',
            },
            bases=(shared.base_model.BaseModel, models.Model),
        ),
    ]
